// Zaze dialogue content — statically pre-paginated.
// Each entry is one physical leaf of the book; pagination was computed
// by rendering every leaf against the real page box (see /tools/paginate.py)
// so that no page overflows and no paragraph is dropped.
const DIALOGUE_PAGES = [
  {
    "title": "Zaze, or On Greatness — Editorial Note",
    "body": "        <header class=\"leaf__heading\">\n          <h1>ΖΑΖΗΣ</h1>\n          <p class=\"work-title\">ἢ Περὶ Μεγέθους &middot; Zaze, or On&nbsp;Greatness</p>\n        </header>\n\n        <p class=\"frontmatter__label\">Editorial Note</p>\n        <p class=\"frontmatter__note\">\n          The dialogue printed below is a modern composition in imitation of\n          Plato. The Stephanus numeration employed throughout is an\n          editorial reconstruction intended solely for ease of citation and\n          should not be confused with the pagination of Henri Estienne&rsquo;s\n          (Stephanus&rsquo;) 1578 edition of Plato. The references have\n          therefore been assigned according to argumentative divisions in\n          the manner of modern classical editions.\n        </p>\n\n        <div class=\"divider\" aria-hidden=\"true\">\n          <span class=\"divider__mark\">&middot;Ζ&middot;</span>\n        </div>\n\n        <p class=\"frontmatter__label\" style=\"text-align:center;\">Dramatis Personae</p>\n        <ul class=\"dramatis-personae\">\n          <li>Socrates</li>\n          <li>Glaucon</li>\n          <li>Zaze of Epirus</li>\n        </ul>\n\n        <p class=\"book__toc-link\" style=\"text-align:center;\">\n          <a href=\"../index.html\">&#8618; Return to the title page</a>\n        </p>\n\n      "
  },
  {
    "title": "Stephanus 327a–327e &middot; Zaze, or On Greatness",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>327a–327e</span>\n        </div><p class=\"stephanus\">327a</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>Whence come you, Socrates? For you seem to have escaped no small multitude; and indeed I thought you had remained among them.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You judged rightly, Glaucon. For I had gone to the Agora intending only to converse with a certain shield-maker concerning a promise he had made me. But before I had reached him I found the place occupied by a crowd much greater than is usual, not unlike that which gathers when the rhapsodes recite Homer at the Panathenaea. Since I am always eager to learn what causes men to assemble, whether wisely or foolishly, I drew near.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>Then you have heard already what has lately been resolved among the Greeks.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>I heard many voices; but because they were eager to speak all at once, I understood little. Some appeared to praise a man, others to marvel at him, while a few laughed, as though the matter admitted alike of seriousness and jest. Tell me, therefore, quietly what has happened.</p>\n</section><p class=\"stephanus\">327b</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>A gathering of philosophers and distinguished men has lately been held at Athens, attended by envoys and lovers of wisdom from many cities. After much discussion they declared that among all the living there is none greater than Zaze the Young of Epirus.</p>\n</section>"
  },
  {
    "title": "Stephanus 327a–327e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>327a–327e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You surprise me. For I had supposed that such judgments belonged rather to later generations than to those who live beside the man in question. Tell me, then: by what measure did they compare him with the others?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>They spoke of many names—Alexander of Macedon, Cyrus the Persian, Pyrrhus of Epirus, Homer the poet, and Euclid the geometer—and yet concluded that Zaze surpassed them all in a certain art which he himself first established.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You mention men whose excellences differ greatly. One conquered nations, another composed verses, another discovered demonstrations, another excelled in war. Did they find some single measure common to all these, by which they could determine who was greatest?</p>\n</section><p class=\"stephanus\">327c</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>That, Socrates, I cannot say. For whenever one man praised military prowess, another praised wisdom; and when another esteemed the founding of cities above both, a fourth declared that the shaping of men’s souls was the highest achievement. Yet despite their disagreements, they all arrived at the same conclusion.</p>\n</section>"
  },
  {
    "title": "Stephanus 327a–327e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>327a–327e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then either they were wonderfully harmonious, or wonderfully fortunate.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>You may inquire of the man himself, if you wish. For here comes Zaze, attended by several young men, who seem unwilling to leave his company.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Let us receive him, then, not as judges of his reputation, but as fellow inquirers. For perhaps we shall learn from him what sort of excellence persuaded so many men to speak with one voice; or, if we do not learn that, we shall at least discover what they believed themselves to have found.</p>\n</section><p class=\"stephanus\">327d</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Good day, Socrates; good day, Glaucon. I could not help but hear my own name as I approached. I hope I have not become the subject of accusation before the court of philosophy.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Be at ease, Zaze. We have accused you of nothing—unless it be counted a fault to receive too much praise. Whether that praise has been justly bestowed is precisely what I, being ignorant, desire to examine with you. For men now proclaim you the greatest among the living, and I should count it no small gain if, by conversing with so celebrated a man, I might come to understand what greatness itself is.</p>\n</section>"
  },
  {
    "title": "Stephanus 327a–327e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>327a–327e</span>\n        </div><p class=\"stephanus\">327e</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Tell me then, Zaze, for I would begin where my ignorance is greatest. As I crossed the Agora I heard not only your own name proclaimed, but another title joined to it, strange to my ears. They called you, if I heard rightly, “the Goat.” Tell me, was the crier mocking you, or honouring you?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Honouring me, Socrates; though I confess the title sounds less dignified than those who bestow it imagine.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then I am relieved. For I feared the Athenians had suddenly resolved that goats were wiser than philosophers, and that old men like myself must either grow horns or remain forever ignorant.</p>\n</section><div class=\"stage-direction\">(The young men laughed.)</div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>You know very well that he speaks of no animal.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then perhaps I know less than you suppose. Come, Zaze; rescue me before these youths conclude that age has carried off what little understanding I possessed.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>The name is shortened speech. They mean that I am the Greatest of All Time.</p>\n</section>"
  },
  {
    "title": "Stephanus 328a–328e &middot; Zaze, or On Greatness",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>328a–328e</span>\n        </div><p class=\"stephanus\">328a</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Ah! You have translated one mystery into another.</p>\n<p>For I understand the letters better than the thing itself.</p>\n<p>Tell me, what is it to be greatest?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>To surpass all others in excellence.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>A noble answer. But tell me this.</p>\n<p>Does a man surpass others because many declare that he does, or because he truly excels?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Because he truly excels.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then if all Athens proclaimed me the finest flute-player in Greece, while I scarcely knew how to distinguish a flute from a shepherd’s pipe, should their shouting make me a musician?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Certainly not.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then praise follows excellence, but does not produce it.</p>\n</section>"
  },
  {
    "title": "Stephanus 328a–328e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>328a–328e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>That seems necessary.</p>\n</section><p class=\"stephanus\">328b</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Yet another difficulty remains.</p>\n<p>They tell me that those who honoured you compared you with Homer, Alexander, Cyrus, Pyrrhus, and Euclid.</p>\n<p>Now I confess myself puzzled.</p>\n<p>For unless Homer secretly conquered Asia, or Alexander composed epics while marching, I do not know by what measure such men could be judged together.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Perhaps they were not comparing the kinds of their achievements.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Explain yourself.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Every art possesses its own excellence.</p>\n<p>The poet is measured differently from the geometer, and the geometer differently from the general.</p>\n<p>Yet there may still be something common among them.</p>\n</section>"
  },
  {
    "title": "Stephanus 328a–328e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>328a–328e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>What is that?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>The greatness of what they accomplished.</p>\n</section><p class=\"stephanus\">328c</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>I do not yet understand.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Consider this.</p>\n<p>One man invents a method by which a village prospers.</p>\n<p>Another establishes laws for an entire people.</p>\n<p>A third composes verses which every generation continues to recite.</p>\n<p>Their works differ.</p>\n<p>Yet each leaves behind something larger than himself.</p>\n<p>Surely we may ask whose work transformed human life most deeply.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>By Hera, you do not seem to defend yourself without thought.</p>\n<p>For there is something persuasive in what you say.</p>\n<p>Yet let us examine it.</p>\n<p>Does everything that changes the lives of many thereby become great?</p>\n</section>"
  },
  {
    "title": "Stephanus 328a–328e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>328a–328e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>I do not suppose so.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>A plague changes many lives.</p>\n<p>So does a famine.</p>\n<p>So too a tyrant.</p>\n<p>Shall we therefore call them greatest?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Certainly not.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then we must seek something besides magnitude.</p>\n<p>For it appears that greatness is not measured merely by how far a thing extends, but also by what sort of thing it is.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>Then perhaps greatness belongs to whatever benefits the greatest number.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Perhaps, Glaucon.</p>\n<p>But before we ask how many ought to benefit, should we not first discover what benefit itself is?</p>\n<p>Otherwise we resemble merchants who count their coins before learning whether they are gold or merely gilded bronze.</p>\n</section>"
  },
  {
    "title": "Stephanus 328a–328e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>328a–328e</span>\n        </div><p class=\"stephanus\">328d</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Yet perhaps we proceed too hastily.</p>\n<p>For before we inquire whether any man deserves to be called greatest, ought we not first determine whether greatness itself is one thing, or many?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Why do you ask that?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Because Homer is praised for poetry, Solon for laws, Alexander for conquest, Euclid for demonstrations, and Pyrrhus for war.</p>\n<p>Now if each excelled in a different pursuit, I do not yet see how one may simply pronounce one greater than another.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Nor should one do so lightly.</p>\n<p>Yet I do not think the difficulty is impossible.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You encourage me.</p>\n<p>Show me the road, then, if you already see it.</p>\n</section>"
  },
  {
    "title": "Stephanus 328a–328e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>328a–328e</span>\n        </div><p class=\"stephanus\">328e</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Perhaps men become comparable, not because they practise the same art, but because they alter the world in unequal measure.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>We have already spoken somewhat in that direction.</p>\n<p>Yet I fear we left the matter unfinished.</p>\n<p>For if alteration alone makes greatness, disease would rival philosophy.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>I do not mean alteration simply.</p>\n<p>I mean alteration proceeding from excellence.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then excellence remains the measure after all.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>It must.</p>\n<p>But excellence sometimes appears in discovering something which did not previously exist.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Ah!</p>\n<p>Now perhaps we approach what those Athenians intended.</p>\n</section>"
  },
  {
    "title": "Stephanus 329a–329e &middot; Zaze, or On Greatness",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>329a–329e</span>\n        </div><p class=\"stephanus\">329a</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Tell me, then.</p>\n<p>Is your claim that you have become great because you have founded a new art?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>That is what many believe.</p>\n<p>Whether they judge rightly is another question.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You answer more cautiously than many celebrated men.</p>\n<p>Most, when praised, eagerly accept every ornament placed upon them.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Or perhaps they fear appearing ungrateful if they refuse.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>A subtle distinction.</p>\n<p>Yet gratitude and truth are not always companions.</p>\n<p>Come then.</p>\n<p>What is this art?</p>\n<p>For unless we first understand the thing itself, we shall scarcely judge the worth of its founder.</p>\n</section>"
  },
  {
    "title": "Stephanus 329a–329e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>329a–329e</span>\n        </div><p class=\"stephanus\">329b</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>The art I established consists in composing what we call edits.</p>\n<p>These unite words, images, music, history, and performance into one composition, so that great deeds become present before those who were absent from them.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You speak as though one craft had swallowed many others.</p>\n<p>Tell me.</p>\n<p>Have you discovered a new art?</p>\n<p>Or merely persuaded several old ones to labour together?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Does the answer matter?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>I think so.</p>\n<p>For if a man invites flute-players, dancers, and cooks to the same banquet, we praise his hospitality, but we do not therefore call him the inventor of a new craft.</p>\n</section><div class=\"stage-direction\">(The company laughed.)</div><p class=\"stephanus\">329c</p>"
  },
  {
    "title": "Stephanus 329a–329e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>329a–329e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Nor would I.</p>\n<p>Yet suppose another man gathered physicians, builders, mathematicians, and sailors for the founding of a colony.</p>\n<p>Would you say he had merely assembled them?</p>\n<p>Or would you admit that the city itself possesses an order which none of those arts alone could produce?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You answer by asking another question.</p>\n<p>A dangerous habit.</p>\n<p>If you continue in this way, these young men will soon suppose that you are Socrates, while I am left to answer in your place.</p>\n</section><div class=\"stage-direction\">(The company laughed.)</div><div class=\"stage-direction\">Yet perhaps it is not a dangerous habit after all, but only a philosophical one.</div><div class=\"stage-direction\">Tell me, then.</div><div class=\"stage-direction\">What makes the city one rather than many?</div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Its purpose.</p>\n<p>For each craft lays aside its own private end in order to contribute to a common one.</p>\n</section>"
  },
  {
    "title": "Stephanus 329a–329e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>329a–329e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then according to you, unity belongs not to the materials employed, but to the end toward which they are directed.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Precisely.</p>\n</section><p class=\"stephanus\">329d</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Let us examine whether that is true.</p>\n<p>The physician employs knives, herbs, diet, and exercise.</p>\n<p>Yet we do not divide him into four craftsmen.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Because all serve health.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>The pilot likewise makes use of winds, ropes, stars, rudders, and sails.</p>\n<p>Yet he remains one pilot.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Because they all serve navigation.</p>\n</section>"
  },
  {
    "title": "Stephanus 329a–329e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>329a–329e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Very well.</p>\n<p>Perhaps I chose the wrong example earlier.</p>\n<p>For a banquet possesses no single end beyond pleasure.</p>\n<p>A city does.</p>\n<p>And perhaps your art claims to resemble the city more than the banquet.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>That is better said.</p>\n<p>For I do not merely gather arts together.</p>\n<p>I command them toward one purpose.</p>\n</section><p class=\"stephanus\">329e</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then tell us that purpose.</p>\n<p>For unless we know it, we still do not know whether yours is one art or several disguised as one.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Its purpose is twofold.</p>\n<p>To preserve glory.</p>\n<p>And to awaken it.</p>\n</section>"
  },
  {
    "title": "Stephanus 329a–329e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>329a–329e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Two purposes?</p>\n<p>Take care.</p>\n<p>For whenever someone says “two,” I immediately begin to wonder whether he has described one thing or two.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>They are not separate.</p>\n<p>The memory of noble deeds invites imitation.</p>\n<p>To preserve greatness is already to encourage it.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Perhaps.</p>\n<p>Yet perhaps not.</p>\n<p>For many remember without becoming better.</p>\n<p>And many admire what they ought rather to condemn.</p>\n<p>We shall therefore have to inquire, not only what your art remembers, but what it teaches men to love.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>Then we have not yet discovered its nature.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>No, Glaucon.</p>\n<p>Only where the real difficulty begins.</p>\n</section>"
  },
  {
    "title": "Stephanus 330a–330e &middot; Zaze, or On Greatness",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>330a–330e</span>\n        </div><p class=\"stephanus\">330a</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Let us return, then, to what you have just said.</p>\n<p>You claim that your art preserves glory and awakens it.</p>\n<p>Tell me first about the former.</p>\n<p>Does the deed exist before the composition?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>In most cases, yes.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Like the Trojan War before Homer?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Just so.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then Homer did not make Achilles brave.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>No.</p>\n<p>Yet neither would many Greeks have admired Achilles had Homer remained silent.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You mean that remembrance completes what action begins?</p>\n</section>"
  },
  {
    "title": "Stephanus 330a–330e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>330a–330e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>I should say so.</p>\n<p>Many noble deeds perish because no one learns of them.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>That is a striking thought.</p>\n<p>Perhaps memory contributes something to virtue, though I am not yet prepared to say what.</p>\n</section><p class=\"stephanus\">330b</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>But another question follows.</p>\n<p>Is every art that moves the soul therefore beneficial?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Certainly not.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then movement alone cannot be the measure.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>No more than speed is the measure of a journey.</p>\n<p>A man may run swiftly toward a precipice.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Well answered.</p>\n<p>Then tell me what distinguishes good persuasion from bad.</p>\n</section>"
  },
  {
    "title": "Stephanus 330a–330e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>330a–330e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Its object.</p>\n<p>One persuades men toward what is noble.</p>\n<p>The other toward what is base.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You answer readily.</p>\n<p>Perhaps too readily.</p>\n<p>For I suspect that everyone persuading others believes himself to be leading them toward something noble.</p>\n<p>How then shall we distinguish the true guide from the false?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>I do not know.</p>\n<p>For every guide believes he is leading toward what is best.</p>\n</section><div class=\"stage-direction\">(There was silence.)</div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>Then perhaps no art that persuades can ever know whether it persuades rightly.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Take care, Glaucon.</p>\n<p>If that were true, philosophy herself would be in greater danger than rhetoric.</p>\n</section>"
  },
  {
    "title": "Stephanus 330a–330e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>330a–330e</span>\n        </div><p class=\"stephanus\">330c</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Must every artist answer that question?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>What do you mean?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Does the sculptor first discover justice before carving Solon?</p>\n<p>Or the musician first define courage before composing a war-song?</p>\n<p>Surely an art may accomplish its work without first possessing philosophy.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>By Zeus, you compel me to proceed more carefully.</p>\n<p>For perhaps I have demanded too much.</p>\n<p>Tell me instead—</p>\n<p>what must the maker of your compositions know?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>He must know what men are capable of admiring.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Ah.</p>\n<p>Now we approach a dangerous place.</p>\n<p>For cooks also know what men delight in.</p>\n</section>"
  },
  {
    "title": "Stephanus 330a–330e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>330a–330e</span>\n        </div><p class=\"stephanus\">330d</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Then perhaps my art resembles neither medicine nor cookery.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>How so?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>The cook seeks pleasure.</p>\n<p>The physician seeks health.</p>\n<p>But I seek remembrance.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>A third end.</p>\n<p>You surprise me.</p>\n<p>Yet tell me—</p>\n<p>is remembrance itself always good?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>No.</p>\n<p>Some things deserve to be forgotten.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then remembrance is not your true end after all.</p>\n</section>"
  },
  {
    "title": "Stephanus 330a–330e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>330a–330e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Why not?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Because you have already admitted that not everything ought to be remembered equally.</p>\n<p>Therefore remembrance itself must serve something higher.</p>\n</section><p class=\"stephanus\">330e</p><div class=\"stage-direction\">Zaze remained silent for a moment.</div><div class=\"stage-direction\">Then he said,</div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Perhaps.</p>\n<p>Yet if remembrance serves something higher, no city has ever fully understood what that thing is.</p>\n<p>One generation honours lawgivers.</p>\n<p>Another honours conquerors.</p>\n<p>A third honours poets.</p>\n<p>Perhaps remembrance is always searching for the good without wholly finding it.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>A beautiful answer.</p>\n<p>Whether it is true I do not yet know.</p>\n<p>But if it is false, it is at least nobly false.</p>\n</section>"
  },
  {
    "title": "Stephanus 331a–331e &middot; Zaze, or On Greatness",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>331a–331e</span>\n        </div><p class=\"stephanus\">331a</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Now another difficulty occurs to me.</p>\n<p>Suppose two makers of edits portray the same battle.</p>\n<p>One records everything exactly.</p>\n<p>The other omits much, rearranges much, and causes every young man who beholds it to love his city more deeply.</p>\n<p>Which has practised the better art?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>You ask as though the choice were easy.</p>\n<p>I do not think it is.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Nor I.</p>\n<p>Yet answer as best you can.</p>\n</section><p class=\"stephanus\">331b</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>The second.</p>\n<p>If indeed he has made them love what deserves to be loved.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then accuracy is not sufficient?</p>\n</section>"
  },
  {
    "title": "Stephanus 331a–331e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>331a–331e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>No.</p>\n<p>A chronicle and a work of art are not identical.</p>\n<p>The first preserves events.</p>\n<p>The second reveals their meaning.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You distinguish preservation from revelation.</p>\n<p>Explain.</p>\n</section><p class=\"stephanus\">331c</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Imagine a painter.</p>\n<p>He cannot place an entire battlefield upon a single panel.</p>\n<p>He must choose.</p>\n<p>One face.</p>\n<p>One gesture.</p>\n<p>One instant.</p>\n<p>Yet if he chooses wisely, we understand the battle better than if every soldier had been painted.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then selection need not be falsehood.</p>\n</section>"
  },
  {
    "title": "Stephanus 331a–331e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>331a–331e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Quite the contrary.</p>\n<p>Without selection, nothing becomes intelligible.</p>\n</section><p class=\"stephanus\">331d</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You remind me of something.</p>\n<p>When we converse, do we not likewise choose certain arguments while leaving others aside?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Certainly.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then philosophy itself practises a kind of selection.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Would you deny it?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>No.</p>\n<p>But philosophy differs in one respect.</p>\n<p>Whenever she omits something, she hopes that inquiry may later recover it.</p>\n<p>The flatterer omits only what would expose him.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Then the difference lies not in selection, but in honesty.</p>\n</section>"
  },
  {
    "title": "Stephanus 331a–331e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>331a–331e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Perhaps.</p>\n<p>Yet I wonder whether I have spoken correctly.</p>\n<p>For a flatterer also claims to love what appears true to his hearers.</p>\n<p>No—</p>\n<p>let us say instead that philosophy loves being corrected.</p>\n<p>Whether every artist can do the same, I do not yet know.</p>\n<p>Whether those are identical, I am not yet prepared to say.</p>\n</section><p class=\"stephanus\">331e</p><div class=\"stage-direction\">There was silence among them.</div><div class=\"stage-direction\">At length Socrates spoke again.</div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>When we began, I feared your art merely adorned great deeds.</p>\n<p>Now I begin to suspect that it also interprets them.</p>\n<p>Whether every interpretation brings us nearer to truth, or whether some lead us away from it, I cannot yet determine.</p>\n<p>Until we discover what truth itself requires of art, I think we have not yet understood your craft.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>Then we know less than we supposed.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>So it appears.</p>\n<p>Yet perhaps that is the beginning of knowing.</p>\n</section>"
  },
  {
    "title": "Stephanus 332a–332e &middot; Zaze, or On Greatness",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>332a–332e</span>\n        </div><p class=\"stephanus\">332a</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>But perhaps, Zaze, we have examined only the work, while forgetting the workman.</p>\n<p>For every art seems to reflect something of the soul from which it proceeds.</p>\n<p>Tell me, does an art become noble because its practitioner is noble, or does the practitioner become noble by practising the art?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>I do not think either answer is sufficient by itself.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Explain.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Have you not known men who became just through obeying just laws?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Certainly.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Then the work sometimes educates its maker no less than its audience.</p>\n</section>"
  },
  {
    "title": "Stephanus 332a–332e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>332a–332e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Perhaps.</p>\n<p>Though I wonder who first made the laws that educated him.</p>\n<p>For if every work requires a noble maker, and every maker requires a noble work, we seem to move in a circle.</p>\n</section><p class=\"stephanus\">332b</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Yet I have heard something concerning yourself.</p>\n<p>They say that during the war between the Macedonians and those who stood with Athens and Epirus, you did not remain among spectators praising courage from a place of safety.</p>\n<p>Rather, you shared the dangers yourself.</p>\n<p>Is this report true?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>It is.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Why?</p>\n<p>Was it that your art required experience?</p>\n<p>Or that your conscience required action?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Neither entirely.</p>\n<p>I thought it shameful to praise publicly what I refused privately.</p>\n</section>"
  },
  {
    "title": "Stephanus 332a–332e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>332a–332e</span>\n        </div><p class=\"stephanus\">332c</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then you agree that life ought to precede speech.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Not always.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>No?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Many fathers teach courage to sons before they themselves have been tested.</p>\n<p>Many poets have strengthened cities they never defended with weapons.</p>\n<p>Would you deny that they accomplished something noble?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Certainly not.</p>\n<p>Then perhaps I spoke too hastily.</p>\n<p>It seems one may sometimes speak truly before fortune grants the opportunity to act.</p>\n</section><p class=\"stephanus\">332d</p>"
  },
  {
    "title": "Stephanus 332a–332e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>332a–332e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Yet another thought occurs to me.</p>\n<p>Suppose a man continually exhorts others to justice while secretly living unjustly.</p>\n<p>Would his words lose their truth?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Their truth?</p>\n<p>No.</p>\n<p>Their authority?</p>\n<p>Perhaps.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You distinguish carefully.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Must we not?</p>\n<p>For a theorem does not become false because the geometer is greedy.</p>\n<p>Nor does a physician’s remedy cease to heal because he himself neglects moderation.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>By Zeus, you defend your position well.</p>\n<p>Yet I suspect the soul differs from geometry.</p>\n</section><p class=\"stephanus\">332e</p>"
  },
  {
    "title": "Stephanus 332a–332e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>332a–332e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Consider this instead.</p>\n<p>When the physician prescribes medicine, he treats another man’s body.</p>\n<p>But when the teacher praises courage, he presents himself as an example, whether he intends it or not.</p>\n<p>Is that not so?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Often.</p>\n<p>Though not always.</p>\n<p>Some examples teach by imitation.</p>\n<p>Others by warning.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>An unexpected distinction.</p>\n<p>Explain.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Have we not learned moderation from the downfall of tyrants as well as from the lives of good men?</p>\n<p>The wicked also instruct.</p>\n<p>Only differently.</p>\n</section>"
  },
  {
    "title": "Stephanus 333a–333e &middot; Zaze, or On Greatness",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>333a–333e</span>\n        </div><p class=\"stephanus\">333a</p><div class=\"stage-direction\">Socrates smiled.</div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You remind me that the gods have strange methods of education.</p>\n<p>Very well.</p>\n<p>Let us return to your own art.</p>\n<p>Earlier you said that the artist preserves glory.</p>\n<p>Now tell me—</p>\n<p>which is greater?</p>\n<p>The deed?</p>\n<p>Or the remembrance?</p>\n<p>Zaze hesitated.</p>\n<p>Then he answered.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>You ask as though one could stand without the other.</p>\n</section><p class=\"stephanus\">333b</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Can they not?</p>\n<p>Suppose Achilles had fought, but no poet had sung.</p>\n<p>Would he not still have been brave?</p>\n</section>"
  },
  {
    "title": "Stephanus 333a–333e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>333a–333e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Brave?</p>\n<p>Certainly.</p>\n<p>Great?</p>\n<p>I am less certain.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>How can that be?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Because greatness belongs not only to what a man is, but also to what he leaves among men.</p>\n<p>A virtue buried forever resembles a lamp hidden beneath the earth.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You have compelled me to abandon something I assumed at the beginning.</p>\n<p>For I had thought remembrance merely followed greatness, as a shadow follows the body.</p>\n<p>Now I am no longer certain.</p>\n<p>Perhaps remembrance belongs to greatness itself.</p>\n<p>Yet if so, I no longer know what greatness is.</p>\n</section>"
  },
  {
    "title": "Stephanus 333a–333e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>333a–333e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>It gives light.</p>\n<p>But to no one.</p>\n<p>There was silence.</p>\n</section><p class=\"stephanus\">333c</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>That is a powerful image.</p>\n<p>Yet let us beware of it.</p>\n<p>For if a deed becomes great only after it is remembered, then the artist appears greater than the hero.</p>\n<p>Since he bestows greatness.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>I did not say that.</p>\n<p>The artist does not create the light.</p>\n<p>He uncovers it.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Sometimes.</p>\n<p>Yet have we not agreed that he also interprets?</p>\n<p>And whatever interprets also judges.</p>\n</section><p class=\"stephanus\">333d</p>"
  },
  {
    "title": "Stephanus 333a–333e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>333a–333e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Then perhaps artist and hero are partners.</p>\n<p>One performs what ought to be remembered.</p>\n<p>The other discovers how it ought to be remembered.</p>\n<p>Neither is sufficient alone.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Partners?</p>\n<p>Perhaps.</p>\n<p>Yet unequal partners.</p>\n<p>Tell me—</p>\n<p>if every poet vanished tomorrow, would courageous men cease to exist?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>No.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>And if courageous men vanished?</p>\n<p>Would poets still possess anything worthy of singing?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Very little.</p>\n<p>Perhaps nothing.</p>\n</section>"
  },
  {
    "title": "Stephanus 333a–333e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>333a–333e</span>\n        </div><p class=\"stephanus\">333e</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then it seems the deed possesses a certain priority.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Yes.</p>\n<p>But priority is not supremacy.</p>\n<p>The foundation is laid before the roof.</p>\n<p>Yet no one therefore chooses to dwell in a foundation.</p>\n<p>Socrates laughed.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Take care, Zaze.</p>\n<p>You have become rather skilful at escaping my conclusions.</p>\n<p>Whether you escape because they are unsound, or because I pursue them badly, I cannot yet determine.</p>\n<p>But this much has become clear to me.</p>\n<p>The artist depends upon the hero.</p>\n<p>Yet the hero, if wholly forgotten, seems to lose something which belongs to greatness itself.</p>\n<p>What that something is, I do not yet know.</p>\n</section>"
  },
  {
    "title": "Stephanus 334a–334e &middot; Zaze, or On Greatness",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>334a–334e</span>\n        </div><p class=\"stephanus\">334a</p><div class=\"stage-direction\">There was silence among them for some time.</div><div class=\"stage-direction\">At length Socrates spoke.</div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>We have travelled farther than I expected, Zaze.</p>\n<p>When we began, I imagined we should merely examine a title.</p>\n<p>Instead we have found ourselves inquiring into memory, art, truth, and virtue.</p>\n<p>Whether we have approached greatness, or merely wandered around it, I do not yet know.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Nor I.</p>\n<p>Yet I think we are no longer asking the same question with which we began.</p>\n</section><p class=\"stephanus\">334b</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Let us see whether that is so.</p>\n<p>At first we supposed that greatness might be determined by public opinion.</p>\n<p>But we abandoned that.</p>\n<p>For praise follows excellence only when it judges rightly.</p>\n<p>It does not produce excellence.</p>\n</section>"
  },
  {
    "title": "Stephanus 334a–334e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>334a–334e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>We all agreed to that.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then we considered whether greatness lay simply in changing the lives of many.</p>\n<p>Yet disease and tyranny taught us otherwise.</p>\n<p>Magnitude without goodness could not satisfy us.</p>\n</section><p class=\"stephanus\">334c</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Afterwards we turned to your own art.</p>\n<p>We discovered that it is not merely history,</p>\n<p>nor poetry,</p>\n<p>nor music,</p>\n<p>nor rhetoric,</p>\n<p>but an ordering of all these toward one purpose.</p>\n<p>Yet when we attempted to state that purpose, we found ourselves less certain than before.</p>\n<p>For remembrance alone would not suffice.</p>\n<p>Nor admiration.</p>\n<p>Nor persuasion.</p>\n<p>Each required another measure by which it might itself be judged.</p>\n</section>"
  },
  {
    "title": "Stephanus 334a–334e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>334a–334e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>So it appeared.</p>\n</section><p class=\"stephanus\">334d</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Then came perhaps the greatest difficulty.</p>\n<p>We agreed that your art interprets deeds rather than merely preserving them.</p>\n<p>Yet interpretation may either reveal the truth or conceal it.</p>\n<p>And we found no easy mark by which to distinguish one from the other.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>Except that one seeks what is good.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Does it?</p>\n<p>Or does it merely seek what appears good?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>Must every artist answer that question?</p>\n<p>Would it not be enough that he move us toward noble actions?</p>\n</section>"
  },
  {
    "title": "Stephanus 334a–334e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>334a–334e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>If only we always knew beforehand which actions were noble.</p>\n<p>There, Glaucon, lies the whole difficulty.</p>\n<p>For unless appearance and reality always agree, the artist and the philosopher must both labour under the same uncertainty.</p>\n</section><p class=\"stephanus\">334e</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Finally we considered the relation between the deed and its remembrance.</p>\n<p>The hero supplies reality.</p>\n<p>The artist grants endurance.</p>\n<p>Take away either, and something seems lacking.</p>\n<p>Yet which contributes more to greatness we have still not discovered.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Perhaps because each completes what the other begins.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Perhaps.</p>\n<p>Yet if each depends upon the other, we must still ask which deserves the greater praise.</p>\n</section>"
  },
  {
    "title": "Stephanus 335a–335e &middot; Zaze, or On Greatness",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>335a–335e</span>\n        </div><p class=\"stephanus\">335a</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>Then are we no nearer to answering whether Zaze is truly the greatest?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Perhaps nearer than you think.</p>\n<p>For we now understand what such a judgment requires.</p>\n<p>It is no small matter to compare conquerors with poets,</p>\n<p>lawgivers with inventors,</p>\n<p>or artists with philosophers.</p>\n<p>He who claims to have done so ought first to explain by what measure he judges.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>And no one has yet done that.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Not to my satisfaction.</p>\n</section><p class=\"stephanus\">335b</p>"
  },
  {
    "title": "Stephanus 335a–335e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>335a–335e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Then perhaps the honour men bestowed upon me was premature.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Perhaps.</p>\n<p>Yet beware of the opposite error.</p>\n<p>Some men reject praise merely because it embarrasses them.</p>\n<p>That is vanity disguised as modesty.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Then what ought one to do?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Accept honours as one accepts favourable winds.</p>\n<p>Gratefully.</p>\n<p>But without supposing they guarantee arrival.</p>\n</section><p class=\"stephanus\">335c</p>"
  },
  {
    "title": "Stephanus 335a–335e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>335a–335e</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>Then who shall judge greatness?</p>\n<p>The multitude?</p>\n<p>Posterity?</p>\n<p>Or philosophy?</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>A difficult question.</p>\n<p>The multitude often judges first.</p>\n<p>Posterity often judges differently.</p>\n<p>Philosophy judges most slowly of all.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>Then philosophy would often arrive too late.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Better late than falsely early.</p>\n<p>Yet perhaps even philosophy sometimes waits longer than wisdom requires.</p>\n<p>Perhaps because she refuses to vote before the inquiry has ended.</p>\n</section>"
  },
  {
    "title": "Stephanus 335a–335e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>335a–335e</span>\n        </div><div class=\"stage-direction\">(The company smiled.)</div><p class=\"stephanus\">335d</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>You have often spoken against reputation.</p>\n<p>Yet is not philosophy herself remembered only through reputation?</p>\n<p>Had no one preserved your conversations, Socrates, who would question us now?</p>\n<p>There was silence.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>You have repaid me generously.</p>\n<p>Throughout our conversation I treated remembrance as though it merely accompanied truth, like a herald following a king.</p>\n<p>But perhaps I have spoken carelessly.</p>\n<p>For unless truth is remembered, it is often defeated by falsehood.</p>\n<p>Perhaps remembrance does not merely accompany truth.</p>\n<p>Perhaps it guards it.</p>\n<p>Whether it also creates it, I still cannot say.</p>\n</section>"
  },
  {
    "title": "Stephanus 335a–335e &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>335a–335e</span>\n        </div><p class=\"stephanus\">335e</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>But this much I think we may safely say.</p>\n<p>Titles neither make men great nor prevent them from becoming so.</p>\n<p>They are like shadows.</p>\n<p>Sometimes faithful.</p>\n<p>Sometimes distorted.</p>\n<p>It is foolish to pursue the shadow while neglecting the body.</p>\n<p>Yet equally foolish to pretend that shadows reveal nothing about the form that casts them.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Zaze.</span>\n  <p>Then every honour ought to be received as an invitation rather than a conclusion.</p>\n</section><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>Beautifully said.</p>\n</section>"
  },
  {
    "title": "Stephanus 336a–336d &middot; Zaze, or On Greatness",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>336a–336d</span>\n        </div><p class=\"stephanus\">336a</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>For the lover of wisdom does not say,</p>\n<p>“I have reached the summit.”</p>\n<p>He says,</p>\n<p>“I have found another path upward.”</p>\n<p>Perhaps greatness resembles this more than victory.</p>\n<p>Not something possessed,</p>\n<p>but something continually approached.</p>\n<p>Though whether it can ever be fully attained,</p>\n<p>I cannot say.</p>\n</section><p class=\"stephanus\">336b</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>Then our discussion ends in uncertainty.</p>\n</section>"
  },
  {
    "title": "Stephanus 336a–336d &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>336a–336d</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>In a certain kind of uncertainty.</p>\n<p>Not the uncertainty of those who have found nothing,</p>\n<p>but of those who have discovered that the road divides.</p>\n<p>One road begins from noble deeds and seeks remembrance.</p>\n<p>The other begins from remembrance and seeks noble deeds.</p>\n<p>Whether these roads meet upon the summit,</p>\n<p>or only seem to do so while we are still below,</p>\n<p>I do not yet know.</p>\n<p>Until then,</p>\n<p>our journey is unfinished.</p>\n</section><p class=\"stephanus\">336c</p><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Glaucon.</span>\n  <p>What then shall we do?</p>\n</section>"
  },
  {
    "title": "Stephanus 336a–336d &middot; Zaze, or On Greatness — continued",
    "body": "<div class=\"leaf__runninghead\">\n          <span>Zaze &middot; On Greatness</span>\n          <span>336a–336d</span>\n        </div><section class=\"speech\">\n  <span class=\"speech__speaker smallcaps\">Socrates.</span>\n  <p>What every philosopher ought.</p>\n<p>Continue asking.</p>\n<p>For if we cease because the question is difficult,</p>\n<p>we shall remain ignorant.</p>\n<p>But if we cease because we imagine ourselves already wise,</p>\n<p>we shall become ridiculous.</p>\n<p>I know of no greater danger.</p>\n</section><p class=\"stephanus\">336d</p><div class=\"closing-narrative\">\n          <p>Thus they ended their conversation. Zaze departed with those who had accompanied him (Germanen) to Epirus, still disputing quietly among themselves. Glaucon walked beside Socrates in silence.</p>\n          <p>After they had gone some distance, he said, “Do you believe we shall ever discover what greatness truly is?”</p>\n          <p>Socrates smiled. “I do not know. But I think we have discovered why it is so difficult to discover.” And they continued toward the city.</p>\n        </div>"
  }
];
